# Site settings
title: "Michelle Yang Resume"
description: "Michelle Yang's Resume."

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Michelle Yang"
resume_title:                   "Production Manager"
resume_contact_email:           "yiqiyang97@gmail.com"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
resume_section_projects:        false
resume_section_skills:          true
resume_section_recognition:     false
resume_section_links:           false
resume_section_associations:    false

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  # resume_github_url:            "https://github.com/twitnic"
  # resume_twitter_url:           "http://twitter.com/Twitt_Nic"
#  resume_dribbble_url:          "https://dribbble.com/jag"
  # resume_facebook_url:          "https://www.facebook.com/DominicRichter"
  resume_linkedin_url:          "https://www.linkedin.com/in/michelle-yiqi-yang-0511/"
  # resume_instagram_url:         "https://www.instagram.com/twitnic/"
  # resume_website_url:           "http://twitnic.de"

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
