# Site settings
title: "Michelle Yang Resume"
description: "Michelle Yang's Resume."

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Michelle Yang"
resume_title:                   "Production Manager"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "yiqiyang97@gmail.com"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone:       "778-881-2073"
resume_contact_address:         "Vancouver, BC"

resume_header_contact_info:     "Vancouver, BC • 778-881-2073 • yiqiyang97@gmail.com"
display_header_contact_info:    "true"

resume_header_intro: "<p>I kicked off my career in on-set production, contributing to projects like <em>The Grand Tour</em> (Amazon) and <em>Race Across the World</em> (BBC). Transitioning to the CG world, I've moved up from assistant to production manager in virtual production. Working at a tech startup, I collaborate closely with all departments, gaining an all-rounded understanding of the real-time pipeline. My core duties involve project planning and execution, communication and team building. Dedicated to staying at the forefront, I constantly learn new tech and project management skills, aiming to make impactful contributions to the industry.</p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
resume_section_projects:        false
resume_section_skills:          false
resume_section_recognition:     false
resume_section_links:           false
resume_section_associations:    false
# resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  # resume_github_url:            "https://github.com/jglovier/resume-template"
  # resume_twitter_url:           "http://twitter.com/jglovier"
  # resume_dribbble_url:          "https://dribbble.com/jag"
  # resume_facebook_url:          "insert Facebook URL here"
  resume_linkedin_url:          "https://www.linkedin.com/in/michelle-yiqi-yang-0511/"
  # resume_instagram_url:         "insert your Instagram URL here"
  # resume_website_url:           "http://joelglovier.com"
  # resume_medium_url:            "https://medium.com/@jglovier"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
